#pragma once

//From glfw3.h
#define SYR_MOUSE_BUTTON_1         0
#define SYR_MOUSE_BUTTON_2         1
#define SYR_MOUSE_BUTTON_3         2
#define SYR_MOUSE_BUTTON_4         3
#define SYR_MOUSE_BUTTON_5         4
#define SYR_MOUSE_BUTTON_6         5
#define SYR_MOUSE_BUTTON_7         6
#define SYR_MOUSE_BUTTON_8         7
#define SYR_MOUSE_BUTTON_LAST      SYR_MOUSE_BUTTON_8
#define SYR_MOUSE_BUTTON_LEFT      SYR_MOUSE_BUTTON_1
#define SYR_MOUSE_BUTTON_RIGHT     SYR_MOUSE_BUTTON_2
#define SYR_MOUSE_BUTTON_MIDDLE    SYR_MOUSE_BUTTON_3

#define SYR_ARROW_CURSOR		0x00036001
#define SYR_IBEAM_CURSOR		0x00036002
#define SYR_CROSSHAIR_CURSOR	0x00036003
#define SYR_HAND_CURSOR			0x00036004
#define SYR_HRESIZE_CURSOR		0x00036005
#define SYR_VRESIZE_CURSOR		0x00036006